name: Build

on:
  workflow_dispatch:
  pull_request:

env:
  DOTNET_CORE_VERSION: 6.0.x
  PACT_BROKER_BASE_URL: ${{ secrets.PACTFLOW_URL }}
  PACT_BROKER_TOKEN: ${{ secrets.PACTFLOW_TOKEN }}
  PACT_BROKER_PUBLISH_VERIFICATION_RESULTS: true
  GIT_BRANCH: ${{ github.ref }}
  GIT_COMMIT: ${{ github.sha }}
  # ${{ secrets.STACK_ID }}
  PACTICIPANT: product-service

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK ${{ env.DOTNET_CORE_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Restore Packages
        run: dotnet restore

      - name: Build Application
        run: dotnet build --no-restore

      - name: Run Tests
        shell: pwsh
        run: '&.scripts/dotnet/run-tests.ps1'

  can-i-deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - run: docker pull pactfoundation/pact-cli:latest
      - name: Can I deploy?
        run: |
          PACT_CLI="docker run --rm -e PACT_BROKER_BASE_URL -e PACT_BROKER_TOKEN pactfoundation/pact-cli:latest"
          @"${PACT_CLI}" broker can-i-deploy \
            --pacticipant ${PACTICIPANT} \
            --version ${GIT_COMMIT} \
            --to stage

  deploy:
    runs-on: ubuntu-latest
    needs: can-i-deploy
    steps:
      - uses: actions/checkout@v2
      
      - run: docker pull pactfoundation/pact-cli:latest

      - name: Deploy
        run: echo "Deploy to Stage"

      - name: Deploy
        run: |
          PACT_CLI="docker run --rm -e PACT_BROKER_BASE_URL -e PACT_BROKER_TOKEN pactfoundation/pact-cli:latest"
          "${PACT_CLI}" broker create-version-tag \
            --pacticipant ${PACTICIPANT} \
            --version ${GIT_COMMIT} \
            --tag stage